version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
  backend:
    build: ../../
    ports:
      - '8082:80'
    volumes:
      - files:/var/lib/app/files

volumes:
  database:
  files:
