version: "3.8"

services:
  static:
    extends:
      file: ../../images/static/deployments/dev/docker-compose.yml
      service: static
  mongo:
    extends:
      file: ../../images/backend/deployments/dev/docker-compose.yml
      service: mongo
  backend:
    extends:
      file: ../../images/backend/deployments/dev/docker-compose.yml
      service: backend
  admin_panel:
    extends:
      file: ../../images/admin_panel/deployments/dev/docker-compose.yml
      service: admin_panel
