version: "3.8"

services:
  static:
    image: nginx
    volumes:
      - ../../dev_volumes/files:/usr/share/nginx/html
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ../../dev_volumes/database:/data/db
    ports:
      - "27017:27017"
  backend:
    image: node:16.14.2
    working_dir: /opt/app
    volumes:
      - ../../images/backend:/opt/app
      - ../../images/backend/node_modules:/opt/app/node_modules
      - ../../images/backend/dist:/opt/app/dist
      - ../../dev_volumes/files:/opt/files
    command: bash -c "npm i --quiet --ignore-scripts && npm run start:dev"
  proxy:
    build: ../../images/proxy/dev
    ports:
      - "8080:80"
    restart: always
  
