version: "3.8"

services:
  build_game_socket:
    extends:
      file: ../../libraries/game_socket/deployments/dev/docker-compose.yml
      service: build_game_socket
  static:
    extends:
      file: ../../images/static/deployments/dev/docker-compose.yml
      service: static
  backend:
    extends:
      file: ../../images/backend/deployments/dev/docker-compose.yml
      service: backend
  admin_panel:
    extends:
      file: ../../images/admin_panel/deployments/dev/docker-compose.yml
      service: admin_panel
