version: "3.8"

services:
  auth:
    extends:
      file: ../../auth/deployments/prod/docker-compose.yml
      service: auth
  static:
    extends:
      file: ../../static/deployments/prod/docker-compose.yml
      service: static
  backend:
    extends:
      file: ../../backend/deployments/prod/docker-compose.yml
      service: backend

volumes:
  files:
