version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
  backend:
    build: ../../images/backend
    ports:
      - '443:80'
    volumes:
      - files:/opt/app/files
    environment:
      - HTTPS=1

volumes:
  files:
  database:
