version: "3.8"

services:
  static:
    extends:
      file: ../../images/static/deployments/prod/docker-compose.yml
      service: static
  backend:
    extends:
      file: ../../images/backend/deployments/prod/docker-compose.yml
      service: backend
  admin_panel:
    extends:
      file: ../../images/admin_panel/deployments/prod/docker-compose.yml
      service: admin_panel

volumes:
  files:
