version: "3.8"

services:
  static:
    image: nginx
    volumes:
      - files:/usr/share/nginx/html
  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
  backend:
    build: ../../images/backend
    volumes:
      - files:/opt/files
    environment:
      - HTTPS=1
  proxy:
    build: ../../images/proxy
    ports:
      - "443:80"
    restart: always

volumes:
  files:
  database:
