version: "3.8"

services:
  static:
    image: nginx
    volumes:
      - files:/usr/share/nginx/html
    ports:
      - "8080:80"
  mongo:
    image: mongo
    restart: always
    volumes:
      - database:/data/db
  backend:
    build: ../../images/backend
    ports:
      - '8082:80'
    volumes:
      - files:/opt/app/files
  admin_panel:
    build: ../../images/admin_panel
    ports:
      - "8083:80"

volumes:
  files:
  database:
